# Generated by Django 5.1.4 on 2024-12-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('custom_view_client', 'Can view client')]},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('custom_view_mailing', 'Can view mailing')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('custom_view_message', 'Can view message')]},
        ),
    ]
